# Skills 知识蒸馏流水线
name: skills-distill
description: 从外部信息源蒸馏 Skill 文档
version: 1.0.0

stages:
  - id: ingest
    name: 采集
    description: 获取并解析信息源内容
    inputs:
      - source_url  # 从流水线参数获取
    outputs:
      - artifacts/{pipeline_id}/ingest/result.json
    quality_checks:
      - content_not_empty
      - valid_format
    on_fail: abort

  - id: classify
    name: 分类
    description: 分析内容类型，判断可提取性
    depends_on: [ingest]
    inputs:
      - artifacts/{pipeline_id}/ingest/result.json
    outputs:
      - artifacts/{pipeline_id}/classify/analysis.json
    quality_checks:
      - extractable_patterns >= 1
    on_fail: retry

  - id: extract
    name: 提取
    description: 从内容中提取可复用模式
    depends_on: [classify]
    inputs:
      - artifacts/{pipeline_id}/classify/analysis.json
    outputs:
      - artifacts/{pipeline_id}/extract/patterns.json
      - artifacts/{pipeline_id}/extract/snippets/
    quality_checks:
      - pattern_count >= 3
      - pattern_count <= 30
    on_fail: retry

  - id: assemble
    name: 组装
    description: 生成 SKILL.md 草稿
    depends_on: [extract]
    inputs:
      - artifacts/{pipeline_id}/extract/patterns.json
    outputs:
      - artifacts/{pipeline_id}/assemble/SKILL-draft.md
    quality_checks:
      - has_required_sections
    on_fail: retry

  - id: validate
    name: 验证
    description: 质量评分和最终检查
    depends_on: [assemble]
    inputs:
      - artifacts/{pipeline_id}/assemble/SKILL-draft.md
    outputs:
      - artifacts/{pipeline_id}/validate/report.json
      - Core/skills/{category}/{skill_name}/SKILL.md  # 最终产物
    quality_checks:
      - score >= 24
    on_fail: retry

settings:
  max_retries_per_stage: 3
  stage_timeout_minutes: 30
  parallel_execution: false
